/*
 * generated by Xtext
 */
package com.devoxx2012.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IzpackRuntimeModule extends com.devoxx2012.xtext.AbstractIzpackRuntimeModule {

}
