/*
* generated by Xtext
*/
package com.devoxx2012.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IzpackUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.devoxx2012.xtext.ui.internal.IzpackActivator.getInstance().getInjector("com.devoxx2012.xtext.Izpack");
	}
	
}
