/*
* generated by Xtext
*/
package com.devoxx2012.xtext.demo1.ui.contentassist;

import com.devoxx2012.xtext.demo1.ui.contentassist.AbstractDemo1ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Demo1ProposalProvider extends AbstractDemo1ProposalProvider {

}
