/*
 * generated by Xtext
 */
package com.devoxx2012.xtext.demo1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Demo1UiModule extends com.devoxx2012.xtext.demo1.ui.AbstractDemo1UiModule {
	public Demo1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
