/*
 * generated by Xtext
 */
package com.devoxx2012.xtext.demo1;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Demo1RuntimeModule extends com.devoxx2012.xtext.demo1.AbstractDemo1RuntimeModule {

}
