/*
 * generated by Xtext
 */
package com.devoxx2012.xtext.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class IzpackScopeProvider extends XtypeScopeProvider {

}
