/*
* generated by Xtext
*/
package com.devoxx2012.xtext.demo1.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.devoxx2012.xtext.demo1.services.Demo1GrammarAccess;

public class Demo1Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Demo1GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.devoxx2012.xtext.demo1.parser.antlr.internal.InternalDemo1Parser createParser(XtextTokenStream stream) {
		return new com.devoxx2012.xtext.demo1.parser.antlr.internal.InternalDemo1Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public Demo1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Demo1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
