/*
* generated by Xtext
*/
package com.devoxx2012.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class IzpackOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
