/*
* generated by Xtext
*/
package com.devoxx2012.xtext.demo1;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Demo1UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.devoxx2012.xtext.demo1.ui.internal.Demo1Activator.getInstance().getInjector("com.devoxx2012.xtext.demo1.Demo1");
	}
	
}
