/*
 * generated by Xtext
 */
package com.devoxx2012.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IzpackUiModule extends com.devoxx2012.xtext.ui.AbstractIzpackUiModule {
	public IzpackUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
