/*
* generated by Xtext
*/
package com.devoxx2012.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.devoxx2012.xtext.services.IzpackGrammarAccess;

public class IzpackParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IzpackGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.devoxx2012.xtext.parser.antlr.internal.InternalIzpackParser createParser(XtextTokenStream stream) {
		return new com.devoxx2012.xtext.parser.antlr.internal.InternalIzpackParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Installer";
	}
	
	public IzpackGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IzpackGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
